run:
  timeout: 5m
output:
  formats:
    - `colored-line-number`
    - `github-actions`
linters:
  enable-all: false
  disable-all: true
  enable:
    - vet
    - goimports
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - revive
    - unused
    - gofmt
    - whitespace
    - misspell
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
issues:
  fix: true
  exclude-dirs:
    - api/proto
    - clients/java
    - clients/js
    - docs
    - scripts
    - ui
severity:
  default-severity: error
