version: "2"
run:
  timeout: 5m
formatters:
  enable:
    - goimports
    - gofmt
linters:
  enable:
    - govet
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - unused
    - whitespace
    - misspell
    - errcheck
    - staticcheck
  exclusions:
    paths:
      - clients/java
      - clients/js
      - docs
      - scripts
      - ui
      - gen
