# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in stencil.gemspec
gemspec

gem "rake", "~> 13.0"
gem "http", "4.4.1"

group :test do
  gem "simplecov", ">= 0.9"
  gem "rspec", "~> 3.0"
  gem "rubocop", "~> 1.7"
  gem "pry"
end
