// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	schema "github.com/raystack/stencil/core/schema"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// SchemaProvider is an autogenerated mock type for the Provider type
type SchemaProvider struct {
	mock.Mock
}

// ParseSchema provides a mock function with given fields: format, data
func (_m *SchemaProvider) ParseSchema(format string, data []byte) (schema.ParsedSchema, error) {
	ret := _m.Called(format, data)

	var r0 schema.ParsedSchema
	if rf, ok := ret.Get(0).(func(string, []byte) schema.ParsedSchema); ok {
		r0 = rf(format, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schema.ParsedSchema)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(format, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSchemaProvider creates a new instance of SchemaProvider. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewSchemaProvider(t testing.TB) *SchemaProvider {
	mock := &SchemaProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
