// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IsSearchRequest_Version is an autogenerated mock type for the isSearchRequest_Version type
type IsSearchRequest_Version struct {
	mock.Mock
}

// isSearchRequest_Version provides a mock function with given fields:
func (_m *IsSearchRequest_Version) isSearchRequest_Version() {
	_m.Called()
}
