// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	schema "github.com/odpf/stencil/core/schema"
)

// ParseFn is an autogenerated mock type for the parseFn type
type ParseFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ParseFn) Execute(_a0 []byte) (schema.ParsedSchema, error) {
	ret := _m.Called(_a0)

	var r0 schema.ParsedSchema
	if rf, ok := ret.Get(0).(func([]byte) schema.ParsedSchema); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schema.ParsedSchema)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
