// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/odpf/stencil/server/domain"
	mock "github.com/stretchr/testify/mock"

	schema "github.com/odpf/stencil/server/schema"
)

// ParsedSchema is an autogenerated mock type for the ParsedSchema type
type ParsedSchema struct {
	mock.Mock
}

// Format provides a mock function with given fields:
func (_m *ParsedSchema) Format() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetCanonicalValue provides a mock function with given fields:
func (_m *ParsedSchema) GetCanonicalValue() *domain.SchemaFile {
	ret := _m.Called()

	var r0 *domain.SchemaFile
	if rf, ok := ret.Get(0).(func() *domain.SchemaFile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SchemaFile)
		}
	}

	return r0
}

// IsBackwardCompatible provides a mock function with given fields: _a0
func (_m *ParsedSchema) IsBackwardCompatible(_a0 schema.ParsedSchema) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(schema.ParsedSchema) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsForwardCompatible provides a mock function with given fields: _a0
func (_m *ParsedSchema) IsForwardCompatible(_a0 schema.ParsedSchema) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(schema.ParsedSchema) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsFullCompatible provides a mock function with given fields: _a0
func (_m *ParsedSchema) IsFullCompatible(_a0 schema.ParsedSchema) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(schema.ParsedSchema) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
