// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/odpf/stencil/server/domain"
	mock "github.com/stretchr/testify/mock"
)

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

// SearchSchemas provides a mock function with given fields: _a0, _a1
func (_m *SearchService) SearchSchemas(_a0 context.Context, _a1 *domain.SearchSchemasRequest) (*domain.SearchSchemasResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *domain.SearchSchemasResponse
	if rf, ok := ret.Get(0).(func(context.Context, *domain.SearchSchemasRequest) *domain.SearchSchemasResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SearchSchemasResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.SearchSchemasRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
