// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	search "github.com/odpf/stencil/core/search"
	mock "github.com/stretchr/testify/mock"
)

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

// Search provides a mock function with given fields: _a0, _a1
func (_m *SearchService) Search(_a0 context.Context, _a1 *search.SearchRequest) (*search.SearchResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *search.SearchResponse
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest) *search.SearchResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*search.SearchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *search.SearchRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
