// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeStencilServiceServer is an autogenerated mock type for the UnsafeStencilServiceServer type
type UnsafeStencilServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedStencilServiceServer provides a mock function with given fields:
func (_m *UnsafeStencilServiceServer) mustEmbedUnimplementedStencilServiceServer() {
	_m.Called()
}
