name: "Lint"

on: [push, pull_request]

jobs:
  golangci:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - name: Crete empty build directory
        run: touch ui/build/.gitkeep
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64

  codeql:
    name: "Analyze with CodeQL"
    runs-on: "ubuntu-latest"
    permissions:
      actions: "read"
      contents: "read"
      security-events: "write"
    strategy:
      fail-fast: false
      matrix:
        language: ["go"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "github/codeql-action/init@v1"
        with:
          languages: "${{ matrix.language }}"
      - uses: "github/codeql-action/autobuild@v1"
      - uses: "github/codeql-action/analyze@v1"
