name: Release Stencil JS Client
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish-js-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@odpf"
      - run: npm install
        working-directory: clients/js
      - run: npm publish --access public
        working-directory: clients/js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
