on: 
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: make test
