name: Test stencil JS client
on:
  push:
    paths:
      - "clients/js/**"
    branches:
      - master
  pull_request:
    paths:
      - "clients/js/**"
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Install dependencies
        run: npm ci
        working-directory: clients/js
      - name: Test
        run: npm test
        working-directory: clients/js
